= GLOBUS LS(1)

== NAME

globus ls - List endpoint directory contents

== SYNOPSIS

*globus ls* ['OPTIONS'] 'ENDPOINT_ID[:PATH]'


== DESCRIPTION

The *globus ls* command lists files and subdirectories on an endpoint. If no
path is given, the default directory on that endpoint will be used.

POSIX style globbing using the wildcard characters ? (matches any single
character) and * (matches any string, including the empty string) is allowed
in the final component of the PATH. If you want to use literall * or ?
characters, the --no-globbing option disables this feature.

include::include/cli_autoactivate.adoc[]


== OPTIONS

*-a, --all*::

Show hidden files and directories that start with '.'

*-l, --long*::

Long form tabular output similar to 'ls -l'.

*-r, --recursive*::

Do a recursive listing similar to 'ls -R' only goes as deep as allowed by
the --recursive-depth-limit. Note that this can quickly become a very expensive
operation and may take a significant amount of time to complete or even fail on
rate limits.

*--recursive-depth-limit* INTEGER::

Set the depth limit when using the --recursive option. Defaults to 3 if not
given.

*--orderby* FIELD::

Order results by the given field name in ascending order. The field name
may either be as shown with --long output (see OUTPUT), or a json key.

*--no-globbing*::

Disable globbing in the final component of the PATH, allowing * and ? to be
used as literal characters instead of wildcards.

include::include/common_options.adoc[]


== OUTPUT

If using text output files and directories are printed with one entry per
line in alphabetical order.  Directories are always displayed with a
trailing '/'.

If using --long text output a table is shown with the following fields, any of
which can be used as an argument to --orderby:

- 'Permissions'
- 'User'
- 'Group'
- 'Size'
- 'Last Modified'
- 'File Type'
- 'Filename'


== EXAMPLES

List files and dirs in your default directory on an endpoint.

----
$ ep_id=ddb59aef-6d04-11e5-ba46-22000b92c6ec
$ ls $ep_id
----

List files and dirs on a specific path on an endpoint.

----
$ ep_id=ddb59aef-6d04-11e5-ba46-22000b92c6ec
$ ls $ep_id:/share/godata/
----


include::include/exit_status.adoc[]
