= GLOBUS TRANSFER(1)

== NAME

globus transfer - Submit a transfer task

== SYNOPSIS

*globus transfer* ['OPTIONS'] -- SOURCE_ENDPOINT_ID:SOURCE_PATH DEST_ENDPOINT_ID:DEST_PATH

*globus transfer* ['OPTIONS'] SOURCE_ENDPOINT_ID DEST_ENDPOINT_ID --batch *<* 'INPUT_LINE(s)'...

== DESCRIPTION

The *globus transfer* command submits an asynchronous task that copies files
and/or directories between endpoints.

*globus transfer* has two modes. Single target, which transfers one
file or one directory, and batch, which takes in several lines to transfer 
multiple files or directories. See "Batch Input" below for more information.

*globus transfer* will always place the dest files in a
consistent, deterministic location.  The contents of a source directory will
be placed inside the dest directory.  A source file will be copied to
the dest file path, which must not be an existing  directory.  All
intermediate / parent directories on the dest will be automatically
created if they don't exist.

By default, if the file or directory at SOURCE_PATH is a symbolic link, it is
followed, and no other symbolic links are followed, transfered, or created on
the destination endpoint. This behavior can be changed with the '--symlink' and
'--recursive-symlinks' options.

include::include/cli_autoactivate.adoc[]


== Batch Input

If you use SOURCE_PATH and DEST_PATH without the --batch flag, you
will submit a single-item transfer task. This has behavior similar to
'cp' across endpoints.

Using '--batch', *globus transfer* can submit a task which transfers
multiple files directories or symlinks. Paths to transfer are taken from stdin.
Lines are split on spaces, respecting quotes, and every line is treated as
a separate item to transfer.

Lines are of the form
[--recursive] [--symlink] SOURCE_PATH DEST_PATH
Empty lines and comments beginning with '#' are ignored.

'--recursive' and '--symlink' are mutually exclusive options that tell transfer
to treat SOURCE_PATH as a dir to be transfered recursively, or a symlink that
should be transfered as is rather than followed, respectively.
Please note that these options cannot be used with the the command level
'--recursive' and '--symlink' options despite sharing names and behavior, as
the command level options are mutually exclusive with batch input.

Batch only requires a SOURCE_ENDPOINT and a DEST_ENDPOINT with the original
command before passing lines on stdin, but if you pass SOURCE_PATH and/or
DEST_PATH in the original command, these paths will be used as prefixes to
their respective paths on stdin.


== OPTIONS

*--batch*::

Starts batch mode input for transfers, which takes lines in the form 
[--recursive] [--symlink] SOURCE_PATH DEST_PATH from stdin to transfer multiple
files, directories, and/or symlinks. See "Batch Input" above for more
information.

*-r, --recursive*::

If SOURCE_PATH and DEST_PATH are both directories, do a recursive transfer
of all files and directories inside of the source directory to the destination
directory. For batch input each directory must use the '--recursive' option at
the batch level, as this option is mutually exclusive with
'--batch' at the command level. This option is also mutually
exclusive with '--symlink'.

*--symlink*::

Keep the symlink at SOURCE_PATH as a symlink, and create it on the destination
endpoint. For batch input each symlink to be treated this way must use the
'--symlink' option at the batch level, as this option is mutually exclusive
with '--batch' at the command level. This option is also mutually
exclusive with '--recursive'.

*--recursive-symlinks [keep|copy|ignore]*::

Choose how transfer task will handle symlinks on source endpoint
during recursive transfers. Defaults to ignore.
+
*keep* will create the symlinks on the destination endpoint.
+
*copy* will copy all data symlinks point to to the destination endpoint.
+
*ignore* will skip all symlinks.

*-s, --sync-level [exists|size|mtime|checksum]*::

Set the level at which the transfer task will decide to replace a file at the
destination with a file at the source with the same name. If not set, files
at the destination will be replaced by default.
+
*exists* will only copy files that do not exist at the destination
+
*size* will replace a file if the size of the destination file does not match
the size of the source file
+
*mtime* will replace a file if the timestamp of the destination file is older
than the timestamp of the source file
+
*checksum* will replace a file if the source and destination files have
different checksums.

*--preserve-mtime*::

Preserve the modification time of files transfered. Note that directories
will not have their modification times preserved.

*--verify-checksum / --no-verify-checksum*::

After transfer, verify that the source and destination file checksums match. 
If they don’t, re-transfer the entire file and keep trying until it succeeds. 
Defaults to True.

*--encrypt*::

Encrypt the transfer data channel. If either the source or the destination
endpoints has force_encryption set this will be done automatically.

*--delete*::

Delete extraneous files and directories in the dest directory.  Only
applies to recursive directory transfers.  For example, a recursive transfer of
/some/source/dir/ to /tmp/mydir/ will ensure /tmp/mydir/ will have no files not
in /some/source/dir/.  All other files in /tmp outside of /tmp/mydir/ are left
alone.

include::include/task_submission_options.adoc[]

include::include/common_options.adoc[]


== EXAMPLES

Transfer a single file:
----
$ source_ep=ddb59aef-6d04-11e5-ba46-22000b92c6ec
$ dest_ep=ddb59af0-6d04-11e5-ba46-22000b92c6ec
$ globus transfer $source_ep:/share/godata/file1.txt $dest_ep:~/mynewfile.txt
----

Transfer a directory recursively:

----
$ source_ep=ddb59aef-6d04-11e5-ba46-22000b92c6ec
$ dest_ep=ddb59af0-6d04-11e5-ba46-22000b92c6ec
$ globus transfer $source_ep:/share/godata/ $dest_ep:~/mynewdir/ --recursive
----

Transfer a symlink at /path/to/symlink as a symlink rather than transferring
the file or directory it links to.

----
$ source_ep=ddb59aef-6d04-11e5-ba46-22000b92c6ec
$ dest_ep=ddb59af0-6d04-11e5-ba46-22000b92c6ec
$ globus transfer $source_ep:/path/to/symlink $dest_ep:~/symlink --symlink
----

Use the batch input method to transfer multiple files dirs and/or symlinks:

----
$ source_ep=ddb59aef-6d04-11e5-ba46-22000b92c6ec
$ dest_ep=ddb59af0-6d04-11e5-ba46-22000b92c6ec
$ globus transfer $source_ep $dest_ep --batch
/share/godata/file1.txt ~/myfile1.txt
/share/godata/file2.txt ~/myfile2.txt
/share/godata/file3.txt ~/myfile3.txt
/share/godata ~/mygodatadir -r
# the line bellow transfers the symlink as a symlink
# rather than transfering the target of the symlink
/share/symlinks/symlink ~/mysymlink --symlink
<EOF>
----

Recursively transfer the contents of a directory linked to by the symlink
at /path/to/symlink to the destination endpoint's home directory while keeping
any further symlinks as symlinks on the destination endpoint.

----
$ source_ep=ddb59aef-6d04-11e5-ba46-22000b92c6ec
$ dest_ep=ddb59af0-6d04-11e5-ba46-22000b92c6ec
$ globus transfer $source_ep:/path/to/symlink $dest_ep:~/ --recursive --recursive-symlinks keep
----

include::include/exit_status.adoc[]